name: JavaScript CI CD Flow Example
on: workflow_dispatch
jobs:
  deployAndMerge:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run JavaScript
          run: node ../utilities/index.js